apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
    name: database-persistent-volume-claim
spec:
    accessModes:
        ## can be write only from one node
        - ReadWriteOnce
    resources:
        requests:
            storage: 1Gi